rootdir = /home/jesu4059/snewpdag-fastlike
configdir = $(rootdir)/snewpdag/data/fastlike

executable = $(configdir)/runtest.sh

arguments = $(configdir)/quick.csv 2

condout = /data/snoplus/lucas/snout/condor
error   = $(condout)/$(ClusterID)-$(Process)-err.txt
output  = $(condout)/$(ClusterID)-$(Process)-out.txt
log     = $(condout)/$(ClusterID)-$(Process)-log.txt

request_cpus   = 1
request_memory = 4096M

queue